# Generated by Django 4.0.6 on 2022-08-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_userprofile_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='car_image',
            field=models.ImageField(null=True, upload_to='carimages'),
        ),
    ]
