# Generated by Django 4.0.6 on 2022-08-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_cars_car_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='year',
            field=models.CharField(max_length=120),
        ),
    ]
