# Generated by Django 4.1 on 2022-09-14 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_messages_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='phone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone_number', to='cars.userprofile'),
        ),
    ]
