# Generated by Django 4.1 on 2022-09-14 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_messages_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='phone',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
