# Generated by Django 4.1 on 2022-09-14 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0009_alter_messages_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='phone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone_no', to=settings.AUTH_USER_MODEL),
        ),
    ]
